/**
 * List of source clips to join, in order.
 *
 * Workflow:
 * 1. Drop your recorded video into `public/videos/` (e.g. `clip-1.mp4`).
 * 2. Generate its subtitles: `npm run transcribe -- clip-1.mp4`
 *    (writes `public/captions/clip-1.json`).
 * 3. Add an entry below. `captionsFile` is optional — omit it for clips
 *    that shouldn't have subtitles.
 */
export type ClipDefinition = {
  /** File name inside `public/videos/` */
  fileName: string;
  /** Human-readable label, only used for comments/organization */
  label: string;
  /** File name inside `public/captions/`, generated by `npm run transcribe` */
  captionsFile?: string;
};

export const clips: ClipDefinition[] = [
  // { fileName: "clip-1.mp4", label: "Entrada al museo", captionsFile: "clip-1.json" },
  // { fileName: "clip-2.mp4", label: "Sala principal", captionsFile: "clip-2.json" },
];
