import React, { useEffect, useMemo, useState } from "react";
import {
  AbsoluteFill,
  continueRender,
  delayRender,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from "remotion";
import type { Caption } from "@remotion/captions";
import { createTikTokStyleCaptions } from "@remotion/captions";

/**
 * Renders word-by-word subtitles for the given captions, timed relative to
 * the start of the <Sequence> this is rendered inside (i.e. `captions`
 * should already be local to the clip, not offset by earlier clips).
 */
export const Subtitles: React.FC<{ captions: Caption[] }> = ({ captions }) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const timeMs = (frame / fps) * 1000;

  const { pages } = useMemo(
    () =>
      createTikTokStyleCaptions({
        captions,
        combineTokensWithinMilliseconds: 1200,
      }),
    [captions],
  );

  const activePage = pages.find(
    (page) => timeMs >= page.startMs && timeMs < page.startMs + page.durationMs,
  );

  if (!activePage) {
    return null;
  }

  return (
    <AbsoluteFill className="items-end justify-center pb-24">
      <div className="max-w-[80%] rounded-xl bg-black/70 px-6 py-3 text-center text-4xl font-bold text-white">
        {activePage.tokens.map((token) => {
          const isActive = timeMs >= token.fromMs && timeMs < token.toMs;
          return (
            <span
              key={token.fromMs}
              className={isActive ? "text-yellow-300" : undefined}
            >
              {token.text}
            </span>
          );
        })}
      </div>
    </AbsoluteFill>
  );
};

/**
 * Loads a captions JSON file (as generated by `npm run transcribe`) from
 * `public/captions/` and renders it with <Subtitles>. Use this inside a
 * clip's <Sequence> instead of <Subtitles> directly.
 */
export const ClipCaptions: React.FC<{ captionsFile: string }> = ({
  captionsFile,
}) => {
  const [captions, setCaptions] = useState<Caption[] | null>(null);
  const [handle] = useState(() =>
    delayRender(`Loading captions/${captionsFile}`),
  );

  useEffect(() => {
    fetch(staticFile(`captions/${captionsFile}`))
      .then((res) => res.json())
      .then((data: Caption[]) => {
        setCaptions(data);
        continueRender(handle);
      })
      .catch((err) => {
        console.error(`Failed to load captions/${captionsFile}`, err);
        continueRender(handle);
      });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [captionsFile]);

  if (!captions) {
    return null;
  }

  return <Subtitles captions={captions} />;
};
